# Set-ChromeAsDefault.ps1
# This script attempts to set Google Chrome as the default web browser for HTTP and HTTPS
# protocols for the Default User Profile.
#
# !!! IMPORTANT LIMITATIONS !!!
# Programmatically changing default browser associations in Windows 10/11 is HIGHLY UNRELIABLE
# due to OS protections. Windows uses a hash-based system to verify user intent for
# default browser choices (UserChoice key). Simply setting ProgId registry values often fails
# or results in Windows prompting the user to confirm.
#
# THE MICROSOFT-SUPPORTED METHOD for default associations is using an XML file generated by
# `Dism /Online /Export-DefaultAppAssociations` and applied with
# `Dism /Online /Import-DefaultAppAssociations` or via LayoutModification.xml.
# This script DOES NOT use that method and is provided as a best-effort attempt only.
# EXPECT THIS SCRIPT TO POTENTIALLY NOT WORK AS INTENDED on many systems.
#
# Prerequisites:
# - Google Chrome must be installed on the system.

# --- Configuration ---
$chromeProgId = "ChromeHTML" # The Programmatic Identifier for Chrome
$protocols = @("http", "https")

$defaultUserHivePath = "C:\Users\Default\NTUSER.DAT"
$tempHiveKeyName = "TempDefaultUser_Chrome" # Unique temporary key name
$associationsPathBaseInHive = "Software\Microsoft\Windows\Shell\Associations\UrlAssociations"

# Function to write messages to host (visible in TS logs)
function Write-Log {
    param([string]$Message, [string]$Severity = "INFO")
    Write-Host "[$Severity] $Message"
}

Write-Log "Starting Set-ChromeAsDefault.ps1 for Default User Profile."
Write-Log "IMPORTANT: Review script header regarding limitations of programmatically setting default browsers." "WARN"

# --- Administrator Privileges Check ---
Write-Log "Checking for Administrator privileges..."
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Log "Administrator privileges are required to modify the Default User profile. Aborting." "ERROR"
    Start-Sleep -Seconds 5
    exit 1
}
Write-Log "Administrator privileges confirmed."

# --- Check if Chrome is Installed ---
Write-Log "Checking if Google Chrome is installed..."
$chromePathFound = $false
$chromePaths = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe"
    # HKCU path is not relevant when checking system-wide installation for Default User context
)
$actualChromePath = $null

foreach ($path in $chromePaths) {
    if (Test-Path $path) {
        $regEntry = Get-ItemProperty -Path $path -Name "(Default)" -ErrorAction SilentlyContinue
        if ($regEntry) {
            $actualChromePath = $regEntry."(Default)"
            if ($actualChromePath -and (Test-Path $actualChromePath -PathType Leaf)) {
                Write-Log "Google Chrome executable found at: $actualChromePath"
                $chromePathFound = $true
                break
            } else {
                 Write-Log "Registry entry found at $path, but the executable path '$actualChromePath' is invalid or not found. Checking next path." "WARN"
            }
        }
    }
}

if (-not $chromePathFound) {
    Write-Log "Google Chrome installation not found in HKLM. Please install Chrome system-wide. Aborting." "ERROR"
    exit 1
}

# --- Validate Default User Hive Path ---
Write-Log "Validating Default User hive path: '$defaultUserHivePath'..."
if (-not (Test-Path $defaultUserHivePath -PathType Leaf)) {
    Write-Log "Default User profile hive '$defaultUserHivePath' not found. Cannot apply settings. Aborting." "ERROR"
    exit 1
}
Write-Log "Default User hive found."

# --- Load Default User Hive, Attempt Modification, and Unload ---
$hiveLoaded = $false
Write-Log "Attempting to load Default User hive from '$defaultUserHivePath' into 'HKLM\$tempHiveKeyName'..."
try {
    reg.exe unload "HKLM\$tempHiveKeyName" >$null 2>&1 # Ensure not already loaded
    reg.exe load "HKLM\$tempHiveKeyName" "$defaultUserHivePath"
    if ($LASTEXITCODE -ne 0) {
        Throw "reg.exe load command failed with exit code $LASTEXITCODE for HKLM\$tempHiveKeyName and $defaultUserHivePath."
    }
    $hiveLoaded = $true
    Write-Log "Default User hive loaded successfully into HKLM\$tempHiveKeyName."

    foreach ($protocol in $protocols) {
        $urlAssociationPathInHive = "HKLM:\$tempHiveKeyName\$associationsPathBaseInHive\$protocol"
        $userChoicePathInHive = "$urlAssociationPathInHive\UserChoice"

        Write-Log "Processing protocol: $protocol in loaded Default User hive."

        # Ensure the base UrlAssociations key for the protocol exists
        if (-not (Test-Path $urlAssociationPathInHive)) {
            try {
                New-Item -Path $urlAssociationPathInHive -Force -ErrorAction Stop | Out-Null
                Write-Log "Created registry key: $urlAssociationPathInHive"
            }
            catch {
                Write-Log "Failed to create registry key '$urlAssociationPathInHive'. Error: $($_.Exception.Message)" "ERROR"
                Write-Log "Skipping $protocol protocol for Default User." "WARN"
                continue
            }
        }

        # Attempt to set the UserChoice ProgId
        try {
            if (-not (Test-Path $userChoicePathInHive)) {
                New-Item -Path $userChoicePathInHive -Force -ErrorAction Stop | Out-Null
                Write-Log "Created registry key: $userChoicePathInHive"
            }
            Set-ItemProperty -Path $userChoicePathInHive -Name "ProgId" -Value $chromeProgId -Type String -Force -ErrorAction Stop
            Write-Log "Successfully set ProgId for $protocol to $chromeProgId in loaded Default User hive."
            Write-Log "NOTE: Windows uses a HASH value in UserChoice to validate this. Without a valid hash, this change may be ignored or reset by the OS." "WARN"
        }
        catch {
            Write-Log "Failed to set ProgId for $protocol in loaded Default User hive. Error: $($_.Exception.Message)" "ERROR"
        }
    }
}
catch {
    Write-Log "Error during Default User hive operations for Chrome default setting: $($_.Exception.Message)" "ERROR"
}
finally {
    if ($hiveLoaded) {
        Write-Log "Unloading Default User hive ('HKLM\$tempHiveKeyName')..."
        [GC]::Collect()
        Start-Sleep -Milliseconds 200
        reg.exe unload "HKLM\$tempHiveKeyName"
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Default User hive unloaded successfully."
        } else {
            Write-Log "Failed to unload Default User hive (HKLM\$tempHiveKeyName). Exit code: $LASTEXITCODE." "WARN"
        }
    }
}

Write-Log "Script 'Set-ChromeAsDefault.ps1' for Default User Profile completed." "INFO"
Write-Log "Changes attempted for new user accounts. Due to Windows restrictions, VERIFY if Chrome is the actual default." "WARN"
Write-Log "For reliable default browser settings, use the XML-based App Association method (DISM Export/Import-DefaultAppAssociations)." "IMPORTANT"

exit 0 # Exit with 0 as the script itself completed, even if the OS doesn't honor the changes.
